version: '3'
services:
  node-hello-world:
    build:
      context: .
      dockerfile_inline: |
        FROM node:latest AS frontend-builder

        WORKDIR /app

        COPY package*.json pnpm-lock.yaml ./
        RUN npm install --force

        COPY . .

        RUN npm run build

        FROM node:latest

        WORKDIR /usr/src/app

        COPY server.cert /usr/src/app/server.cert
        COPY server.key /usr/src/app/server.key

        COPY --from=frontend-builder /app/dist/index.html /usr/src/app/
        COPY --from=frontend-builder /app/dist/assets /usr/src/app/assets/
        COPY --from=frontend-builder /app/dist/assets/ /usr/src/app/assets/
        COPY app.js /usr/src/app/
        COPY hannah.fbx /usr/src/app/
        COPY /entries /usr/src/app/entries
        COPY /src/assets/favicon.png /usr/src/app/assets/

        EXPOSE 80
        EXPOSE 443

        CMD [ "node", "app.js" ]
    ports:
      - "80:80"
      - "443:443"
